In [1]:
print("Hello World!")

Hello World!


In [3]:
#creating numpy/n-d arrays

In [4]:
import numpy as np

In [6]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [9]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

arr3=np.zeros((2,3))
arr3

In [10]:
arr3=np.zeros((2,3))

In [11]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7=np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
arr8=np.arange(5,16,2)

In [18]:
arr8

array([ 5,  7,  9, 11, 13, 15])

In [19]:
arr9=np.linspace(10,20,10)

In [20]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [22]:
#numpy ararys pprooperties and attributes....


In [23]:
arr1.shape

(5,)

In [24]:
arr2.shape

(2, 3)

In [29]:
arr11=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


In [30]:
arr11


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr11.shape

(2, 2, 2)

In [33]:
arr12=np.array([[[1,2],[3,4],[5,6],[7,8]]])
arr12

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [34]:
arr12.shape

(1, 4, 2)

In [35]:
arr11.ndim

3

In [36]:
arr2.ndim

2

In [37]:
arr12.ndim

3

In [38]:
arr1.ndim

1

In [39]:
arr1.size

5

In [40]:
arr11.size

8

In [41]:
arr11.itemsize

4

In [42]:
arr9.itemsize

8

In [43]:
#itemsize=size of the datatype

In [44]:
arr9.dtype

dtype('float64')

In [45]:
arr10.dtype

dtype('float64')

In [46]:
arr8.dtype

dtype('int32')

In [47]:
arr8.astype('float')

array([ 5.,  7.,  9., 11., 13., 15.])