In [1]:
#indexing,slicing,iteration

In [2]:
import numpy as np

In [3]:
arr1=np.arange(24)

In [4]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
arr2=np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
arr4=np.arange(24).reshape(3,8)
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
#reshape() is used to change the shape of the array

In [12]:
arr5=np.array([1,2,3,4,5])

In [13]:
arr5

array([1, 2, 3, 4, 5])

In [14]:
arr5[4]

5

In [16]:
arr5[2:4]

array([3, 4])

In [17]:
arr5[-1]

5

In [18]:
arr2[2]

array([ 8,  9, 10, 11])

In [20]:
arr2[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
arr2[[],[3]]

array([], dtype=int32)

In [26]:
arr2[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [27]:
arr2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [28]:
#indexing=fetching single item from a list or array
#slicing=fetching multiple item(maybe rows or columns)from a list

In [29]:
arr2[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [30]:
arr2[4:,2:]

array([[18, 19],
       [22, 23]])

In [32]:
for i in arr2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [33]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [34]:
#numpy operations

In [35]:
arr6=np.array([1,2,3,4,5,6])
arr7=np.array([4,5,6,7,8,9])

In [37]:
arr6-arr7

array([-3, -3, -3, -3, -3, -3])

In [38]:
arr6*arr7
#vector multipication

array([ 4, 10, 18, 28, 40, 54])

In [39]:
arr6*2

array([ 2,  4,  6,  8, 10, 12])

In [40]:
#scalar multipication

In [41]:
arr7>3

array([ True,  True,  True,  True,  True,  True])

In [43]:
arr8=np.arange(6).reshape(2,3)
arr9=np.arange(6,12).reshape(3,2)

In [1]:
arr8.dot(arr7)

NameError: name 'arr8' is not defined

In [1]:
import numpy as np


In [3]:
arr8.dot(arr7)

NameError: name 'arr8' is not defined

In [4]:
arr8.dot(arr9)

NameError: name 'arr8' is not defined

In [5]:
arr8=np.arange(6).reshape(2,3)
arr9=np.arange(6,12).reshape(3,2)

In [6]:
arr8.dot(arr9)

array([[ 28,  31],
       [100, 112]])

In [7]:
#2*3 dot 3*2

In [8]:
arr1

NameError: name 'arr1' is not defined

In [9]:
arr1=np.arange(24)

In [10]:
arr2=np.arange(24).reshape(6,4)

In [11]:
arr1.dot(arr2)

ValueError: shapes (24,) and (6,4) not aligned: 24 (dim 0) != 6 (dim 0)

In [12]:
arr6=np.array([1,2,3,4,5,6])
arr7=np.array([4,5,6,7,8,9])

In [14]:
arr6.dot(arr7)

154

In [15]:
arr6.dot(arr8)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [16]:
arr8

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr8.max()

5

In [18]:
arr8.min()

0

In [19]:
arr8.min(axis=0)

array([0, 1, 2])

In [20]:
arr8.max(axis=1)

array([2, 5])

In [21]:
arr8.min(axis=1)

array([0, 3])

In [22]:
arr8.sum()

15

In [23]:
arr8.sum(axis=0)

array([3, 5, 7])

In [24]:
arr.mean()

NameError: name 'arr' is not defined

In [25]:
arr8.mean()

2.5

In [26]:
arr8.std()

1.707825127659933

In [27]:
np.sin(arr8)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [28]:
np.median(arr8)

2.5

In [29]:
#object oriented programming
        #stactic-to be called from a class|.mean,.sin
        #dynamic-is defined globally1|np.sin,np,median

In [30]:
np.exp(arr8)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [2]:
#all functions including log,tan ar available
#universal function=np.exp(),np.sqrt(),np.sin()
#unary operators=a-min(),a.sin()