In [1]:
#indexing with boolean arrays

In [2]:
import numpy as np

In [4]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[34, 61, 54,  4,  5],
       [10, 56, 41, 62, 33],
       [59, 81, 10,  1, 50],
       [73, 62, 63, 39, 65]])

In [5]:
arr[0]

array([34, 61, 54,  4,  5])

In [6]:
arr[0][2]

54

In [7]:
#this is how indexing works

In [8]:
#conditional indexing i.e applying condition to your index

In [9]:
arr>50

array([[False,  True,  True, False, False],
       [False,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False,  True]])

In [10]:
(arr>50).shape

(4, 5)

In [11]:
arr1=arr>50

In [12]:
arr1

array([[False,  True,  True, False, False],
       [False,  True, False,  True, False],
       [ True,  True, False, False, False],
       [ True,  True,  True, False,  True]])

In [16]:
#arr1 is a boolean array in which all the items are boolean which is either true(1) or false(0)

In [17]:
arr[arr1]

array([61, 54, 56, 62, 59, 81, 73, 62, 63, 65])

In [18]:
#overlapping arr with arr1
#this will print or display only those items which are true

In [20]:
#the above result is indexing using boolean array also known as filtering as items are filtered out from the array

In [21]:
#also this is not limited and is scalable so more conditions can be applied

In [22]:
arr[(arr>50) & (arr%2!=0)]

array([61, 59, 81, 73, 63, 65])

In [23]:
#x%y!=0 means x modulo y not equal zero

In [27]:
#indexing with boolean arrays gives flexibility in code so that an array can be manipulated in end number of ways in order to fetch the desired result

In [28]:
arr[(arr>50) & (arr%2!=0)]=0
arr

array([[34,  0, 54,  4,  5],
       [10, 56, 41, 62, 33],
       [ 0,  0, 10,  1, 50],
       [ 0, 62,  0, 39,  0]])

In [29]:
#here all the values satisfying the condition is set to zero.
#from here its power can be felt...