In [1]:
#broadcasting

In [2]:
import numpy as np

In [3]:
#scenario 1

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
#scenario 2

a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [7]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [8]:
#here all the rows are added by numpy row-wise i.e all the elements of a4 are added by all the row elements of a4

In [11]:
#this is called broadcasting.
#broadcasting is the ability of nnumpy to perform arithmetic operations on dissimilar arrays i.e arrays of different dimensions.
#otherwise the functionality would be restricted and operation coluud only be performed on same arrays

In [12]:
#rules for broadcasting:

In [15]:
#if x=m and y=n then also operation will take place

#scenario 1

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
#if x=1 and y=n then also operation will take place (same dimension)
#given the condition that the corresponding dimension are same ,in this case 3....


#scenario 2

a5=np.arange(3).reshape(1,3)
a6=np.arange(12).reshape(4,3)

print(a5)
print(a6)

[[0 1 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
a5+a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [22]:
#if y=1 and x=m then also operation will take place
#they are not of same dimension

a7=np.arange(4).reshape(4,1)
a8=np.arange(12).reshape(4,3)

print(a7)
print(a8)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
a7+a8

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [24]:
#if x=1 and y!=n then operation will not take place


a9=np.arange(3).reshape(1,3)
a10=np.arange(16).reshape(4,4)

print(a9)
print(a10)

[[0 1 2]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
a9+a10

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [26]:
#broadcast error since the corresponding dimension are not same.

In [27]:
#if x=1 and n=1 then y==n then operation will take place

a11=np.arange(3).reshape(1,3)
a12=np.arange(3).reshape(3,1)

print(a11)
print(a12)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [28]:
a11+a12

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [29]:
#if x=1 and y=1 then operation will take place no matter what the shape of the array is

a13=np.arange(1).reshape(1,1)
a14=np.arange(20).reshape(4,5)

print(a13)
print(a14)

[[0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [30]:
a13+a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
#if they are of different dimension then also operation will take place

In [32]:
a15=np.arange(4)
a16=np.arange(20).reshape(5,4)

print(a15)
print(a16)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [33]:
a15+a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [34]:
#broadcasting is very intuitive and can't be remembered by the rules...
#also there are various permutations and combinations possible for broadcasting.

In [35]:
#conclusion-broadcasting is the special feature or ability of numpy that allows the user to perform operation on dissimilar arrays...